// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `runtime: compose` settings.
 */
export type ComposeSpec = { file: string, 
/**
 * Subset of compose services to bring up; empty means all.
 */
services: Array<string>, profiles: Array<string>, };
