// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a copied path is materialised. `clone` is a copy-on-write clone where the filesystem
 * supports it (APFS, btrfs, XFS) and a plain copy where it does not — which is what makes
 * carrying a multi-gigabyte `node_modules` or `target` affordable.
 */
export type CopyStrategy = "copy" | "clone" | "symlink";
