// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyStrategy } from "./CopyStrategy";

/**
 * One gitignored path, or glob of paths, carried into a new worktree.
 */
export type CopyRule = { 
/**
 * Glob relative to the repo root (`.env`, `config/*.local.json`, `node_modules`).
 */
pattern: string, strategy: CopyStrategy, };
