// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbAdapter } from "./DbAdapter";
import type { DbSeed } from "./DbSeed";
import type { Runtime } from "./Runtime";

/**
 * A database fork. Recognised today, acted on in a later milestone.
 */
export type DatabaseSpec = { adapter: DbAdapter, version?: string | null, seed?: DbSeed | null, 
/**
 * sqlite: the file copied for each fork.
 */
source?: string | null, 
/**
 * Env var that receives the fork's URL; defaults to `<NAME>_URL`.
 */
env?: string | null, runtime?: Runtime | null, options: { [key in string]: string }, };
