// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The database a fork is made from.
 */
export type DbAdapter = "postgres" | "mysql" | "sqlite" | "redis";
