// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * At most one of `dump`, `sql` or `command`; lint enforces it.
 */
export type DbSeed = { dump?: string | null, sql?: string | null, 
/**
 * Shell command run once against the fresh template (migrations, seeders).
 */
command?: string | null, };
