// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A duration in milliseconds. `Copy`, because it is passed around constantly.
 */
export type Duration = string;
