// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `env_file: .env.canopy` (the default) or `env_file: false`.
 */
export type EnvFile = boolean | string;
