// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { TcpTarget } from "./TcpTarget";

/**
 * Exactly one of `http`, `tcp` or `cmd` must be set; lint enforces it.
 */
export type HealthCheck = { 
/**
 * GET this URL; 2xx and 3xx are healthy. Templates allowed (`${ports.api}`).
 */
http?: string | null, 
/**
 * Connect to this port on localhost. A bare number or `${ports.x}`.
 */
tcp?: TcpTarget | null, 
/**
 * Shell command run in the worktree with the service env; exit 0 is healthy.
 */
cmd?: string | null, interval: Duration, timeout: Duration, 
/**
 * Consecutive failures before the service counts as unhealthy.
 */
retries: number, 
/**
 * Grace period after start during which failures do not count.
 */
start_period: Duration, };
