// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named port. Every key is optional: `web: {}` is a complete declaration.
 */
export type PortSpec = { 
/**
 * Used when free; otherwise allocation walks on from a hash of the branch.
 */
preferred?: number | null, 
/**
 * Restricts allocation to `[from, to]`.
 */
range?: [number, number] | null, description?: string | null, };
