// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeSpec } from "./ComposeSpec";
import type { DockerSpec } from "./DockerSpec";
import type { Duration } from "./Duration";
import type { HealthCheck } from "./HealthCheck";
import type { RestartPolicy } from "./RestartPolicy";
import type { Runtime } from "./Runtime";

/**
 * A long-running process. Needs either `run` or `compose`; lint enforces it.
 */
export type ServiceSpec = { 
/**
 * Shell command, run through `/bin/sh -c`. Required unless `compose:` is set.
 */
run?: string | null, 
/**
 * Relative to the worktree root.
 */
cwd?: string | null, runtime?: Runtime | null, env: { [key in string]: string }, 
/**
 * Named ports this service listens on. Omitted means "infer from the run command and env",
 * which is what [`service_ports`] does.
 */
ports?: Array<string> | null, health?: HealthCheck | null, depends_on: Array<string>, restart: RestartPolicy, 
/**
 * `false` registers the service without starting it with the worktree.
 */
autostart: boolean, docker?: DockerSpec | null, compose?: ComposeSpec | null, stop_signal: string, stop_timeout: Duration, description?: string | null, };
