// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tcp: 5432` and `tcp: "${ports.api}"` are both valid.
 */
export type TcpTarget = number | string;
