// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeSpec = { 
/**
 * Where a worktree goes. `{{ repo }}`, `{{ repo_path }}`, `{{ branch }}`, `{{ name }}`,
 * each optionally `| sanitize`. A relative result resolves against the repo.
 */
path: string, 
/**
 * What a new branch forks from when `--base` is not given. `None` means the repo's
 * current default branch, discovered at the time it is needed.
 */
base?: string | null, };
