// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Runtime } from "./Runtime";

/**
 * What every service inherits before its own keys are applied.
 */
export type Defaults = { runtime: Runtime, env: { [key in string]: string }, };
