// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `runtime: docker` settings. Needs `image` or `dockerfile`; lint enforces it.
 */
export type DockerSpec = { image?: string | null, dockerfile?: string | null, context?: string | null, 
/**
 * Extra `-v` mounts, `host:container[:mode]`.
 */
volumes: Array<string>, args: Array<string>, user?: string | null, workdir: string, };
