// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens when a supervised service exits.
 */
export type RestartPolicy = "never" | "on-failure" | "always";
