/**
 * Text a coding-agent harness writes into the user's lane for its own bookkeeping.
 *
 * Claude Code stores several kinds of machinery as ordinary `user` messages: system reminders,
 * the `/command` echo, local command output, and the `<task-notification>` a background task
 * posts when it finishes. None of it is something the person typed, so a transcript that draws
 * it as a user bubble puts words in their mouth (and, for a notification, opens a turn nobody
 * started). The daemon flags such lines synthetic before mapping; the UI keeps the same test as
 * a guard for logs recorded before the daemon knew a tag.
 */
const HARNESS_TAGS = [
  'system-reminder',
  'task-notification',
  'task-id',
  'command-name',
  'command-message',
  'command-args',
  'local-command-stdout',
  'local-command-stderr',
  'local-command-caveat',
  'bash-input',
  'bash-stdout',
  'bash-stderr',
  'ide_opened_file',
  'ide_selection',
  'user-memory-input',
  'teammate-message',
  'antml:'
] as const

const HARNESS_TAG_PATTERN = new RegExp(`^<(?:${HARNESS_TAGS.map((tag) => tag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})[\\s>]`)

/** Prose the harness uses in place of a tag when it interrupts or resumes a turn. */
const HARNESS_PHRASES = ['[Request interrupted by user', 'Caveat: The messages below were generated by the user while running local commands']

/**
 * Whether `text` is harness bookkeeping rather than something the user said. Leading whitespace
 * is ignored; the check is on how the text *starts* because the harness always leads with its
 * tag, while a person quoting one mid-sentence is still a person.
 */
export function isHarnessText(text: string): boolean {
  const trimmed = text.trimStart()
  if (trimmed === '') return false
  if (HARNESS_TAG_PATTERN.test(trimmed)) return true
  return HARNESS_PHRASES.some((phrase) => trimmed.startsWith(phrase))
}
