/**
 * Generates a starter `canopy.yaml` from what a repo actually contains.
 *
 * The point is a file a developer edits, not one they delete: it is emitted as commented
 * text (not serialised from an object) so the guesses explain themselves, and it is parsed
 * back through `parseCanopyYaml` before being returned — Canopy never hands a user a config
 * its own validator rejects.
 */
import { readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

import { type Ecosystem, parseCanopyYaml, STARTER_CANOPY_YAML } from '@canopy/shared'

interface ScaffoldService {
  name: string
  comment: string
  run?: string
  compose?: string
  env: Record<string, string>
  /** Named port the service listens on; also drives the tcp health check. */
  port?: string
}

interface ScaffoldDatabase {
  name: string
  adapter: 'postgres' | 'mysql' | 'redis' | 'sqlite'
  version?: string
  env?: string
}

interface ScaffoldSetup {
  run: string
  if_changed?: string[]
}

/** A plain YAML scalar where that is unambiguous, single-quoted where it is not. */
function scalar(value: string): string {
  const risky = /^[-?:,[\]{}#&*!|>'"%@`]/.test(value) || /:\s/.test(value) || /\s#/.test(value) || value.trim() !== value || value.length === 0
  return risky ? `'${value.replace(/'/g, "''")}'` : value
}

/** Package manager install command and run prefix, from whichever lockfile is committed. */
function nodeTooling(repoPath: string): { install: string; lockfile: string; run: (script: string) => string } {
  if (existsSync(join(repoPath, 'pnpm-lock.yaml'))) return { install: 'pnpm install --frozen-lockfile', lockfile: 'pnpm-lock.yaml', run: (s) => `pnpm run ${s}` }
  if (existsSync(join(repoPath, 'yarn.lock'))) return { install: 'yarn install --frozen-lockfile', lockfile: 'yarn.lock', run: (s) => `yarn ${s}` }
  const bunLock = ['bun.lockb', 'bun.lock'].find((name) => existsSync(join(repoPath, name)))
  if (bunLock) return { install: 'bun install', lockfile: bunLock, run: (s) => `bun run ${s}` }
  return { install: 'npm ci', lockfile: 'package-lock.json', run: (s) => `npm run ${s}` }
}

/** Dev servers that take `--port` on the command line rather than reading `$PORT`. */
const TAKES_PORT_FLAG = /\b(vite|next|nuxt|astro|remix|svelte-kit|vue-cli-service|ng serve|webpack serve|webpack-dev-server|parcel)\b/

async function readJson(path: string): Promise<Record<string, unknown> | null> {
  try {
    const parsed = JSON.parse(await readFile(path, 'utf8')) as unknown
    return typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : null
  } catch {
    return null
  }
}

/** Compose service names Canopy recognises as an engine it can fork per worktree. */
function guessAdapter(service: string): ScaffoldDatabase['adapter'] | null {
  const name = service.toLowerCase()
  if (/postgres|pgsql|^pg$|timescale/.test(name) || name === 'db' || name === 'database') return 'postgres'
  if (/mysql|mariadb/.test(name)) return 'mysql'
  if (/redis|valkey/.test(name)) return 'redis'
  return null
}

const RESOURCE_NAME = /^[a-z0-9][a-z0-9_-]*$/
const sanitizeName = (name: string): string => {
  const cleaned = name.toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^[^a-z0-9]+/, '')
  return RESOURCE_NAME.test(cleaned) ? cleaned : 'main'
}

/** Renders the descriptor lists into commented YAML. */
function render(services: ScaffoldService[], databases: ScaffoldDatabase[], setup: ScaffoldSetup[], ports: string[], composeFile: string | null): string {
  const lines: string[] = ['version: 1', '# Generated by Canopy from this repo. Everything here is a guess you can edit.', '']

  if (ports.length > 0) {
    lines.push('# Named ports — every worktree gets its own free number. Reference as ${ports.web}.', 'ports:')
    for (const port of ports) lines.push(`  ${port}: {}`)
    lines.push('')
  }

  if (databases.length > 0) {
    lines.push('# Forked per worktree: each branch gets its own copy of the data.', 'databases:')
    for (const db of databases) {
      lines.push(`  ${db.name}:`)
      lines.push(`    adapter: ${db.adapter}`)
      if (db.version) lines.push(`    version: "${db.version}"`)
      if (db.env) lines.push(`    env: ${db.env}`)
      // Redis forks start empty; only the SQL engines have a template worth seeding.
      if (db.adapter !== 'redis') lines.push('    # seed: { dump: ./db/seed.dump }   # template every fork starts from')
    }
    lines.push('')
  }

  if (setup.length > 0) {
    lines.push('# Run once when a worktree is provisioned, with the resolved env.', 'setup:')
    for (const step of setup) {
      lines.push(`  - run: ${scalar(step.run)}`)
      if (step.if_changed && step.if_changed.length > 0) lines.push(`    if_changed: [${step.if_changed.join(', ')}]`)
    }
    lines.push('')
  }

  lines.push('services:')
  if (services.length === 0) lines.push('  # No runnable service was detected — add one, e.g. web: { run: ./start.sh }')
  for (const service of services) {
    lines.push(`  ${service.name}:`)
    lines.push(`    # ${service.comment}`)
    if (service.compose) {
      lines.push('    compose:')
      lines.push(`      file: ${service.compose}`)
    }
    if (service.run) lines.push(`    run: ${scalar(service.run)}`)
    const env = Object.entries(service.env)
    if (env.length > 0) {
      lines.push('    env:')
      for (const [key, value] of env) lines.push(`      ${key}: "${value}"`)
    }
    if (service.port) lines.push(`    health: { tcp: "\${ports.${service.port}}" }`)
    lines.push('    restart: on-failure')
  }
  lines.push('')

  if (composeFile) {
    lines.push(`# The compose stack runs under a per-worktree project name. Use \${ports.x} inside`)
    lines.push(`# ${composeFile} port mappings so two branches never fight over the same host port.`)
    lines.push('')
  }

  lines.push('env_file: .env.canopy')
  return `${lines.join('\n')}\n`
}

/**
 * @param repoPath the primary checkout to inspect.
 * @param detected the project scan (ecosystems, compose file) — the same data the Add-project
 *   dialog shows, so the scaffold agrees with what the user was told the repo is.
 */
export async function scaffoldCanopyYaml(repoPath: string, detected: { ecosystems: Ecosystem[]; compose?: { file: string; services: string[] } }): Promise<string> {
  const services: ScaffoldService[] = []
  const databases: ScaffoldDatabase[] = []
  const setup: ScaffoldSetup[] = []
  const ports: string[] = []
  const used = new Set<string>()
  const claim = (name: string): string => {
    let candidate = name
    let n = 2
    while (used.has(candidate)) candidate = `${name}-${n++}`
    used.add(candidate)
    return candidate
  }
  const claimPort = (name: string): string => {
    if (!ports.includes(name)) ports.push(name)
    return name
  }

  const has = (ecosystem: Ecosystem): boolean => detected.ecosystems.includes(ecosystem)

  if (has('node')) {
    const pkg = await readJson(join(repoPath, 'package.json'))
    const scripts = (pkg?.['scripts'] ?? {}) as Record<string, string>
    const script = ['dev', 'start', 'serve'].find((name) => typeof scripts[name] === 'string')
    const tooling = nodeTooling(repoPath)
    setup.push({ run: tooling.install, if_changed: [tooling.lockfile] })
    if (script) {
      const name = claim('web')
      const port = claimPort('web')
      const flagged = TAKES_PORT_FLAG.test(scripts[script] ?? '')
      services.push({
        name,
        comment: `package.json "${script}" script`,
        run: flagged ? `${tooling.run(script)} -- --port \${ports.${port}}` : tooling.run(script),
        env: flagged ? {} : { PORT: `\${ports.${port}}` },
        port
      })
    }
  }

  if (has('python')) {
    const pyproject = existsSync(join(repoPath, 'pyproject.toml'))
    if (pyproject) setup.push({ run: 'uv sync', if_changed: [existsSync(join(repoPath, 'uv.lock')) ? 'uv.lock' : 'pyproject.toml'] })
    else if (existsSync(join(repoPath, 'requirements.txt'))) setup.push({ run: 'uv pip install -r requirements.txt', if_changed: ['requirements.txt'] })
    const entry = ['main.py', 'app.py'].find((file) => existsSync(join(repoPath, file)))
    if (existsSync(join(repoPath, 'manage.py'))) {
      const name = claim('web')
      const port = claimPort('web')
      services.push({ name, comment: 'Django development server', run: `uv run python manage.py runserver 127.0.0.1:\${ports.${port}}`, env: {}, port })
    } else if (entry) {
      const name = claim('web')
      const port = claimPort('web')
      services.push({ name, comment: `python ${entry}`, run: `uv run python ${entry}`, env: { PORT: `\${ports.${port}}` }, port })
    }
  }

  if (has('rust')) {
    setup.push({ run: 'cargo build', if_changed: ['Cargo.lock'] })
    const name = claim('app')
    const port = claimPort(name)
    services.push({ name, comment: 'cargo run', run: 'cargo run', env: { PORT: `\${ports.${port}}` }, port })
  }

  if (has('go')) {
    if (existsSync(join(repoPath, 'go.sum'))) setup.push({ run: 'go mod download', if_changed: ['go.sum'] })
    const name = claim('app')
    const port = claimPort(name)
    services.push({ name, comment: 'go run .', run: 'go run .', env: { PORT: `\${ports.${port}}` }, port })
  }

  const compose = detected.compose
  if (compose) {
    const name = claim('stack')
    services.push({ name, comment: `docker compose up from ${compose.file}`, compose: compose.file, env: {} })
    const seen = new Set<string>()
    for (const service of compose.services) {
      const adapter = guessAdapter(service)
      if (!adapter) continue
      const dbName = sanitizeName(service === 'db' || service === 'database' ? 'main' : service)
      if (seen.has(dbName)) continue
      seen.add(dbName)
      databases.push({
        name: dbName,
        adapter,
        version: adapter === 'postgres' ? '16' : adapter === 'mysql' ? '8' : adapter === 'redis' ? '7' : undefined,
        env: adapter === 'postgres' ? 'DATABASE_URL' : adapter === 'redis' ? 'REDIS_URL' : undefined
      })
    }
  }

  if (services.length === 0 && databases.length === 0 && setup.length === 0) return STARTER_CANOPY_YAML

  const text = render(services, databases, setup, ports, compose?.file ?? null)
  // Guessing wrong is fine; emitting something the daemon would refuse to load is not.
  return parseCanopyYaml(text).errors.length === 0 ? text : STARTER_CANOPY_YAML
}
